Fruits=[]
print("Initallt List:",Fruits)
f1=input("Enter First Fruit: ")
Fruits.append(f1)
f2=input("Enter Second Fruit: ")
Fruits.append(f2)
f3=input("Enter Third Fruit: ")
Fruits.append(f3)
f4=input("Enter Fourth Fruit: ")
Fruits.append(f4)
f5=input("Enter fifth Fruit: ")
Fruits.append(f5)
f6=input("Enter Sixth Fruit: ")
Fruits.append(f6)
f7=input("Enter Seventh Fruit: ")
Fruits.append(f7)
print("Added List:",Fruits)

