m1=int(input("Marks of Roll.1:"))
m2=int(input("Marks of Roll.2:"))
m3=int(input("Marks of Roll.3:"))
m4=int(input("Marks of Roll.4:"))
m5=int(input("Marks of Roll.5:"))
m6=int(input("Marks of Roll.6:"))
Marks=[m1,m2,m3,m4,m5,m6]
print("Marks Without Sorted:",Marks)
Marks.sort()
print("Marks in Sorting Order:",Marks)
